application: river-module-354
version: 1
runtime: python27
api_version: 1
threadsafe: true

# Other settings here...
automatic_scaling:
  max_idle_instances: 1

handlers:
- url: /css
  static_dir: css

- url: /(.*\.(gif|png|jpg))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg))

- url: /index\.html
  script: menu.html

- url: /menu\.html
  script: menu.html
- url: /*\.html
  script: menu.html